import "./globals.css";
import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/Navbar";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <Navbar />
        <main className="max-w-[1280px] w-full mx-auto px-4">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
