import "./globals.css";
import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { cn } from "@/lib/utils";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(epilogue.className, "bg-neutral-100")}>
        <Navbar />
        <main className="max-w-[1280px] w-full mx-auto px-4">{children}</main>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
